version: 0.2
phases:
  install:
    runtime-versions:
        dotnet: 8.0
  pre_build:
    commands:
      - echo Restoring .NET dependencies...
      - dotnet restore
  build:
    commands:
      - echo Building the .NET project...
      - dotnet build --configuration Release --output ./build-output
  post_build:
    commands:
      - echo Packaging the Lambda function using AWS SAM CLI...
      - sam package --template-file template.yaml --output-template-file packaged-template.yaml
      - echo Build and packaging complete.
artifacts:
  files:
    - packaged-template.yaml
    - build-output/**/*
